name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The CI test job
  test:
    name: ${{ matrix.os }} - GAP ${{ matrix.gap-branch }} ${{ matrix.ABI }} - HPCGAP ${{ matrix.HPCGAP }}
    runs-on: ${{ matrix.os }}-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - master
          - stable-4.11
          - stable-4.10
        GAP_PKGS_TO_BUILD: ['profiling']
        HPCGAP: ['no']
        ABI: ['']
        include:
          - os: ubuntu
            gap-branch: master
            GAP_PKGS_TO_BUILD: ''
            HPCGAP: 'yes'
            ABI: ''
            NO_COVERAGE: 'yes'
          - os: ubuntu
            gap-branch: master
            GAP_PKGS_TO_BUILD: 'profiling'
            HPCGAP: 'no'
            ABI: 32
          - os: macos
            gap-branch: master
            GAP_PKGS_TO_BUILD: 'profiling'
            HPCGAP: 'no'

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
          GAP_PKGS_TO_BUILD: ${{ matrix.GAP_PKGS_TO_BUILD }}
          HPCGAP: ${{ matrix.HPCGAP }}
      - uses: gap-actions/run-test-for-packages@v1
        with:
          NO_COVERAGE: ${{ matrix.NO_COVERAGE }}

  test-cygwin:
    name: "cygwin64 - GAP master - HPCGAP no"
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: windows-latest
    steps:
      - name: "Set git to use UNIX-style line endings"
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-cygwin@master
      - uses: wilfwilson/setup-gap@cygwin
        with:
          GAP_PKGS_TO_BUILD: ''
      - uses: gap-actions/build-pkg@ww/cygwin
      - uses: wilfwilson/run-pkg-tests@cygwin

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
      - uses: gap-actions/compile-documentation-for-packages@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf
